with open('c:/Users/alzia/.gemini/antigravity/scratch/PelayananDigitalDesa/script_admin.html', 'r', encoding='utf-8') as f: lines = f.readlines()

new_content = []
for i in range(len(lines)):
    if i < 686:
        new_content.append(lines[i])

new_content.extend([
    '                    html += \'<div class="flex justify-between items-center bg-slate-50 p-2 rounded-lg border border-slate-101 text-[10px] font-semibold text-slate-700">\' +\\n',
    '                        \'<span><i class="fa-solid fa-check text-emerald-500 mr-1"></i> \' + req + \'</span>\' +\\n',
    '                        \'<button onclick="removeRequirementFromKeperluan(\\\'\' + kep + \'\\\', \' + idx + \')" class="text-red-500 hover:text-red-700 px-1 bg-white border border-slate-200 rounded shadow-sm"><i class="fa-solid fa-xmark"></i></button>\' +\\n',
    '                        \'</div>\';\\n',
    '                });\\n',
    '\\n',
    '                html += \'</div></div>\';\\n',
    '                container.innerHTML += html;\\n',
    '            });\\n',
    '        }\\n',
    '\\n',
    '        function loadBuilderLayananList() {\\n',
    '            var dropdownEditor = document.getElementById(\'builder-select-layanan\');\\n',
    '            if (!dropdownEditor) return;\\n',
    '            dropdownEditor.innerHTML = \'<option value="[+] TAMBAH LAYANAN BARU">[+] TAMBAH LAYANAN BARU</option>\';\\n',
    '\\n',
    '            var layHandler = function (list) {\\n',
    '                window.loadedLayananList = list; // Update dari Layanan Aktif\\n',
    '                list.forEach(function (row) {\\n',
    '                    dropdownEditor.innerHTML += \'<option value="\' + row.nama + \'">\' + row.nama + \'</option>\';\\n',
    '                });\\n',
    '                extractSuggestions(list);\\n',
    '            };\\n',
    '\\n',
    '            if (isGoogleEnv) {\\n',
    '                try {\\n',
    '                    google.script.run.withSuccessHandler(layHandler).getLayananList();\\n',
    '                } catch (e) {\\n',
    '                    layHandler(dummyLayananList);\\n',
    '                }\\n',
    '            } else {\\n',
    '                layHandler(dummyLayananList);\\n',
    '            }\\n',
    '        }\\n',
    '\\n',
    '        function extractSuggestions(list) {\\n',
    '            var nameSet = new Set();\\n',
    '            var reqSet = new Set();\\n',
    '            list.forEach(function (layanan) {\\n',
    '                if (layanan.nama) nameSet.add(layanan.nama);\\n',
    '                if (layanan.persyaratan) {\\n',
    '                    try {\\n',
    '                        var reqObj = JSON.parse(layanan.persyaratan);\\n',
    '                        Object.keys(reqObj).forEach(function(kep) {\\n',
    '                            reqObj[kep].forEach(function(req) {\\n',
    '                                reqSet.add(req);\\n',
    '                            });\\n',
    '                        });\\n',
    '                    } catch(e) {}\\n',
    '                }\\n',
    '            });\\n',
    '\\n',
    '            var nameDatalist = document.getElementById(\'saran-nama-layanan\');\\n',
    '            if (nameDatalist) {\\n',
    '                nameDatalist.innerHTML = \'\';\\n',
    '                nameSet.forEach(function(n) {\\n',
    '                    var opt = document.createElement(\'option\');\\n',
    '                    opt.value = n;\\n',
    '                    nameDatalist.appendChild(opt);\\n',
    '                });\\n',
    '            }\\n',
    '\\n',
    '            var reqDatalist = document.getElementById(\'saran-persyaratan-list\');\\n',
    '            if (reqDatalist) {\\n',
    '                reqDatalist.innerHTML = \'\';\\n',
    '                reqSet.forEach(function(r) {\\n',
    '                    var opt = document.createElement(\'option\');\\n',
    '                    opt.value = r;\\n',
    '                    reqDatalist.appendChild(opt);\\n',
    '                });\\n',
    '            }\\n',
    '\\n',
    '            var reqSuggestions = document.getElementById(\'builder-req-suggestions\');\\n',
    '            if (reqSuggestions) {\\n',
    '                reqSuggestions.innerHTML = \'\';\\n',
    '                reqSet.forEach(function(r) {\\n',
    '                    var btn = document.createElement(\'button\');\\n',
    '                    btn.type = \'button\';\\n',
    '                    btn.className = \'px-2 py-1 bg-slate-100 hover:bg-emerald-100 text-slate-600 hover:text-emerald-700 rounded text-[10px] font-semibold border border-slate-200 transition-colors cursor-pointer\';\\n',
    '                    btn.innerText = r;\\n',
    '                    btn.onclick = function() {\\n',
    '                        var input = document.getElementById(\'builder-req-input\');\\n',
    '                        if(input) {\\n',
    '                            input.value = r;\\n',
    '                            addRequirementToKeperluan();\\n',
    '                        }\\n',
    '                    };\\n',
    '                    reqSuggestions.appendChild(btn);\\n',
    '                });\\n',
    '            }\\n',
    '        }\\n',
    '\\n',
    '        function handleBuilderLayananLoad() {\\n',
    '            var selectVal = document.getElementById(\'builder-select-layanan\').value;\\n',
    '            if (selectVal === "[+] TAMBAH LAYANAN BARU") {\\n',
    '                resetBuilderFormState();\\n',
    '                return;\\n',
    '            }\\n',
    '\\n',
    '            var list = window.loadedLayananList || dummyLayananList;\\n',
    '            var found = list.find(l => l.nama === selectVal);\\n',
    '\\n',
    '            if (found) {\\n',
    '                populateBuilderLayananToEdit(found.id);\\n',
    '            } else {\\n',
    '                resetBuilderFormState();\\n',
    '                document.getElementById(\'builder-select-layanan\').value = selectVal;\\n',
    '                document.getElementById(\'builder-layanan-nama\').value = selectVal;\\n',
    '                document.getElementById(\'wrapper-builder-nama\').classList.add(\'hidden\');\\n',
    '            }\\n',
    '        }\\n'
])

for i in range(693, len(lines)):
    new_content.append(lines[i])

with open('c:/Users/alzia/.gemini/antigravity/scratch/PelayananDigitalDesa/script_admin.html', 'w', encoding='utf-8') as f:
    f.writelines(new_content)
